name: Build findns for Termux (ARMv7)

on:
  workflow_dispatch:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build for Android ARMv7 with CGO
        env:
          CGO_ENABLED: 1
          GOOS: android
          GOARCH: arm
          GOARM: 7
          CC: ${{ github.workspace }}/toolchain/bin/armv7a-linux-androideabi21-clang
        run: |
    
          wget -q https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
          unzip -q android-ndk-r27c-linux.zip
          
          
          android-ndk-r27c/build/tools/make-standalone-toolchain.sh \
            --arch=arm \
            --platform=android-21 \
            --install-dir=${{ github.workspace }}/toolchain

          
          cd cmd
          go build -ldflags "-s -w" -o findns-armv7 .
          mkdir -p ${{ github.workspace }}/output
          cp findns-armv7 ${{ github.workspace }}/output/

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Build ${{ github.run_number }}
          files: output/findns-armv7
